# Generated by Django 5.2.8 on 2025-11-20 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0005_agent_available_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="Module identifier - must match module.name from registry",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "enabled_globally",
                    models.BooleanField(
                        default=False, help_text="Enable this module for all agents"
                    ),
                ),
                (
                    "auto_enable_new_agents",
                    models.BooleanField(
                        default=False, help_text="Automatically enable for new agents"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Global configuration for this module",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgentModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False, help_text="Module is enabled for this agent"
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=False, help_text="Module is available on this agent"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Agent-specific module configuration",
                    ),
                ),
                (
                    "last_check",
                    models.DateTimeField(
                        blank=True, help_text="Last availability check", null=True
                    ),
                ),
                (
                    "last_status",
                    models.JSONField(
                        blank=True, default=dict, help_text="Last status from module"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error if module unavailable"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="agents.agent",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="modules.module"
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Module",
                "verbose_name_plural": "Agent Modules",
                "ordering": ["agent", "module"],
                "unique_together": {("agent", "module")},
            },
        ),
        migrations.CreateModel(
            name="ModuleAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action that was executed", max_length=100
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Parameters passed to action"
                    ),
                ),
                (
                    "initiated_by",
                    models.CharField(
                        blank=True,
                        help_text="User or system that initiated",
                        max_length=100,
                    ),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                (
                    "result_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Result data from action"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Execution time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "agent_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="modules.agentmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Action",
                "verbose_name_plural": "Module Actions",
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["-executed_at"], name="modules_mod_execute_af3df6_idx"
                    ),
                    models.Index(
                        fields=["agent_module", "-executed_at"],
                        name="modules_mod_agent_m_d06a87_idx",
                    ),
                ],
            },
        ),
    ]
