# Generated by Django 5.2.7 on 2025-10-19 12:42
# Note: This migration was duplicate of 0002, converted to no-op

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_agent_agent_api_key_agent_agent_port_and_more"),
    ]

    operations = [
        # No operations - fields already added in 0002
    ]
