# Generated by Django 5.2.8 on 2025-11-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_agent_available_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="mode",
        ),
    ]
