# Generated by Django 5.2.8 on 2025-11-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_remove_agent_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="ssh_key_path",
        ),
        migrations.AddField(
            model_name="agent",
            name="ssh_private_key",
            field=models.TextField(
                blank=True, help_text="SSH private key content (PEM format)"
            ),
        ),
    ]
