# Generated by Django 5.2.8 on 2025-11-21 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0007_remove_agent_ssh_key_path_agent_ssh_private_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="available_modules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of available modules (systeminfo, firewalld, selinux, aide, etc)",
            ),
        ),
        migrations.AddField(
            model_name="agentcommand",
            name="action",
            field=models.CharField(
                blank=True,
                help_text="Action to perform (get_status, add_service, etc)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="agentcommand",
            name="module",
            field=models.CharField(
                blank=True,
                default="firewalld",
                help_text="Module to execute (systeminfo, firewalld, etc)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="agentcommand",
            name="params",
            field=models.JSONField(
                blank=True, default=dict, help_text="Parameters for the action"
            ),
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="command_type",
            field=models.CharField(
                blank=True, help_text="Legacy: stores module.action", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="parameters",
            field=models.JSONField(
                blank=True, default=dict, help_text="Legacy: use params instead"
            ),
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="result",
            field=models.JSONField(
                blank=True, help_text="Command result from agent", null=True
            ),
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("timeout", "Timeout"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="timeout",
            field=models.IntegerField(default=30, help_text="Timeout in seconds"),
        ),
        migrations.AddIndex(
            model_name="agentcommand",
            index=models.Index(
                fields=["agent", "status"], name="agents_agen_agent_i_9b9d58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentcommand",
            index=models.Index(
                fields=["module", "action"], name="agents_agen_module_88fac3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentcommand",
            index=models.Index(
                fields=["-created_at"], name="agents_agen_created_6bbc96_idx"
            ),
        ),
    ]
