# Generated by Django 5.2.8 on 2025-11-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0008_update_agent_command_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="installed_modules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of installed TuxSec module packages (RPMs)",
            ),
        ),
    ]
