# Generated by Django 5.2.8 on 2025-11-25 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0009_add_installed_modules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username (preserved if user deleted)", max_length=150
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "agent_hostname",
                    models.CharField(
                        blank=True,
                        help_text="Agent hostname (preserved if agent deleted)",
                        max_length=255,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Module name (firewalld, selinux, aide, systeminfo, etc)",
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action performed (add_service, create_zone, etc)",
                        max_length=100,
                    ),
                ),
                (
                    "action_category",
                    models.CharField(
                        choices=[
                            ("read", "Read/Query"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("execute", "Execute"),
                            ("configure", "Configure"),
                        ],
                        default="execute",
                        help_text="Category of action for filtering",
                        max_length=20,
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        default=dict, help_text="Parameters used in the action"
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="Result of the action", null=True
                    ),
                ),
                (
                    "success",
                    models.BooleanField(help_text="Whether the action succeeded"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if action failed"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description of the action"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        help_text="Severity level of the action",
                        max_length=20,
                    ),
                ),
                (
                    "before_state",
                    models.JSONField(
                        blank=True,
                        help_text="State before the action (for updates/deletes)",
                        null=True,
                    ),
                ),
                (
                    "after_state",
                    models.JSONField(
                        blank=True,
                        help_text="State after the action (for creates/updates)",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Session ID for grouping related actions",
                        max_length=100,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Custom tags for categorization",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Agent where action was performed (null for system-wide actions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="agents.agent",
                    ),
                ),
                (
                    "command",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="agents.agentcommand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["agent", "-timestamp"],
                        name="agents_audi_agent_i_b349fd_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="agents_audi_user_id_fc2af3_idx",
                    ),
                    models.Index(
                        fields=["module", "action", "-timestamp"],
                        name="agents_audi_module_e9ebd0_idx",
                    ),
                    models.Index(
                        fields=["action_category", "-timestamp"],
                        name="agents_audi_action__fd3162_idx",
                    ),
                    models.Index(
                        fields=["success", "-timestamp"],
                        name="agents_audi_success_7e5f7f_idx",
                    ),
                    models.Index(
                        fields=["severity", "-timestamp"],
                        name="agents_audi_severit_f3fd96_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="agents_audi_timesta_9527cf_idx"
                    ),
                ],
            },
        ),
    ]
