# Generated by Django 5.2.8 on 2025-11-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0010_auditlog"),
    ]

    operations = []
