# Generated by Django 5.2.8 on 2025-11-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0011_add_audit_log_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="firewall_reload_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether firewall configuration changes need reload",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="last_firewall_reload",
            field=models.DateTimeField(
                blank=True, help_text="Last time firewall was reloaded", null=True
            ),
        ),
    ]
