# Generated by Django 5.2.8 on 2025-11-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0012_agent_firewall_reload_required_and_more"),
    ]

    operations = []
