# Generated by Django 5.2.8 on 2025-11-25 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0013_add_reload_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Service name", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Service description"),
                ),
                (
                    "ports",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of ports (e.g., ['80/tcp', '443/tcp'])",
                    ),
                ),
                (
                    "protocols",
                    models.JSONField(
                        blank=True, default=list, help_text="List of protocols"
                    ),
                ),
                (
                    "modules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of netfilter helper modules",
                    ),
                ),
                (
                    "destinations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Destination addresses (IPv4/IPv6)",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="Is this a system service (read-only)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_services",
                        to="agents.agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("agent", "name")},
            },
        ),
    ]
