# Generated by Django 5.2.8 on 2025-11-25 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0014_customservice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IPSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="IPSet name", max_length=100)),
                (
                    "ipset_type",
                    models.CharField(
                        choices=[
                            ("hash:ip", "Hash: IP Address"),
                            ("hash:net", "Hash: Network"),
                            ("hash:mac", "Hash: MAC Address"),
                            ("hash:ip,port", "Hash: IP and Port"),
                            ("hash:net,port", "Hash: Network and Port"),
                        ],
                        help_text="IPSet type",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="IPSet description"),
                ),
                (
                    "entries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of entries (IPs, networks, MACs)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ipsets",
                        to="agents.agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ipsets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("agent", "name")},
            },
        ),
    ]
