# Generated by Django 5.2.8 on 2025-11-25 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0015_ipset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirewallPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Policy name", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Policy description"),
                ),
                (
                    "ingress_zones",
                    models.JSONField(
                        blank=True, default=list, help_text="List of ingress zone names"
                    ),
                ),
                (
                    "egress_zones",
                    models.JSONField(
                        blank=True, default=list, help_text="List of egress zone names"
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("ACCEPT", "Accept"),
                            ("REJECT", "Reject"),
                            ("DROP", "Drop"),
                            ("CONTINUE", "Continue"),
                        ],
                        default="CONTINUE",
                        help_text="Policy target action",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Policy priority (lower is higher priority)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is policy active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firewall_policies",
                        to="agents.agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Firewall Policies",
                "ordering": ["priority", "name"],
                "unique_together": {("agent", "name")},
            },
        ),
    ]
