# Generated by Django 5.2.8 on 2025-11-25 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0016_firewallpolicy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FirewallTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name", max_length=100, unique=True
                    ),
                ),
                ("description", models.TextField(help_text="Template description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("server", "Server"),
                            ("workstation", "Workstation"),
                            ("dmz", "DMZ"),
                            ("network", "Network"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        help_text="Template category",
                        max_length=20,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Template configuration (zones, policies, services, ipsets)",
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, help_text="Available to all users"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Template is active"),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="Number of times template has been applied"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Template tags for filtering",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="agents_fire_categor_f9278e_idx",
                    ),
                    models.Index(
                        fields=["-updated_at"], name="agents_fire_updated_e03b2e_idx"
                    ),
                ],
            },
        ),
    ]
