# Generated by Django 5.2.8 on 2025-11-25 23:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0017_firewalltemplate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ipv",
                    models.CharField(
                        choices=[("ipv4", "IPv4"), ("ipv6", "IPv6")],
                        help_text="IP version (ipv4 or ipv6)",
                        max_length=4,
                    ),
                ),
                (
                    "table",
                    models.CharField(
                        choices=[
                            ("filter", "Filter"),
                            ("nat", "NAT"),
                            ("mangle", "Mangle"),
                            ("raw", "Raw"),
                        ],
                        help_text="iptables table",
                        max_length=10,
                    ),
                ),
                ("chain", models.CharField(help_text="Chain name", max_length=100)),
                ("priority", models.IntegerField(help_text="Rule priority (0-999)")),
                ("args", models.JSONField(help_text="Rule arguments as list")),
                (
                    "description",
                    models.TextField(blank=True, help_text="Rule description"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_rules",
                        to="agents.agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_direct_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["ipv", "table", "chain", "priority"],
                "indexes": [
                    models.Index(
                        fields=["agent", "is_active"],
                        name="agents_dire_agent_i_69250f_idx",
                    ),
                    models.Index(
                        fields=["ipv", "table", "chain"],
                        name="agents_dire_ipv_815ccd_idx",
                    ),
                ],
                "unique_together": {("agent", "ipv", "table", "chain", "priority")},
            },
        ),
    ]
